py36_nose:
  image: python:3.6
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - nosetests -v --nocapture

py37_nose:
  image: python:3.7
  script:
    - apt-get update -q -y
    - pip install -r requirements.txt
    - nosetests -v --nocapture
